version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: "development"
      optional-dependencies:
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/runtime-omx"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
